### ISSUE TITLE
LoadingScreens

### ISSUE THREAD

**Issue by jonni111** [jonni111/LoadingScreens#1]

**Comment by RetroMaja** [comment]
Hey Jonni, is there a way to disable the hints (and the frame) entirely?

**Comment by RetroMaja** [comment]
Also, I did all the loadingscreens stuff, music is working, it shows one of my loadingscreens but I get stuck in the screen.
"Player Unknown (49103228) kicked from server: 49 (Login timed out. (WaitAuthPlayerLoginState))"

**Comment by jonni111** [comment]
проблема решена
